# Generated by Django 3.2.4 on 2021-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bambini', '0004_bambino_codice_fiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='bambino',
            name='immagine',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
