# Generated by Django 3.2.4 on 2021-07-18 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bambini', '0004_bambino_codice_fiscale'),
        ('iscrizioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='bambino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bambini.bambino'),
            preserve_default=False,
        ),
    ]
