# Generated by Django 3.2.4 on 2021-07-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0002_iscrizione_bambino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizione',
            name='is_payed',
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='payed_at',
            field=models.DateField( null=True),
        ),
    ]
