# Generated by Django 3.2.4 on 2021-07-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centri', '0002_alter_centro_options'),
        ('iscrizioni', '0003_auto_20210719_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centri.centro'),
            preserve_default=False,
        ),
    ]
