# Generated by Django 3.2.4 on 2021-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0004_iscrizione_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='payed_at',
            field=models.DateField(null=True),
        ),
    ]
