# Generated by Django 3.2.4 on 2021-07-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centro',
            options={'verbose_name_plural': 'Centri'},
        ),
    ]
