# Generated by Django 3.2.4 on 2021-07-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodi', '0001_initial'),
        ('tariffe', '0002_tariffa_prezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodi.periodo')),
                ('tariffa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffe.tariffa')),
            ],
            options={
                'verbose_name_plural': 'Configurazioni',
            },
        ),
    ]
