# Generated by Django 3.2.4 on 2021-07-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0001_initial'),
        ('configurazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazione',
            name='iscrizione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iscrizioni.iscrizione'),
            preserve_default=False,
        ),
    ]
