# Generated by Django 3.2.4 on 2021-07-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffe', '0002_tariffa_prezzo'),
        ('configurazioni', '0002_configurazione_iscrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazione',
            name='tariffa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariffe.tariffa'),
        ),
    ]
