# Generated by Django 3.2.4 on 2021-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffa',
            name='prezzo',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
